exp_name: 'ENSEMBLE_VIS' # all files will be named/searched with this as prefix
save_dir: '/MS3D/tools/cfgs/target_waymo/exp_ps_dict' 
ps_score_th: # veh,ped,cyc
  pos_th: [0.6,0.4,0.4]
  neg_th: [0.3,0.15,0.15]
pretrained_kbf:
  discard: [1,1,1]
  radius: [1.5, 0.3, 0.2]
  nms: [0.1, 0.5, 0.5]
tracking:
  veh_all_cfg: '/MS3D/tracker/configs/ms3d_configs/veh_kf_giou.yaml'
  veh_static_cfg: '/MS3D/tracker/configs/ms3d_configs/veh_static_kf_iou2d.yaml'
  ped_cfg: '/MS3D/tracker/configs/ms3d_configs/ped_kf_giou.yaml'
  min_dets_for_tracks_veh_all: 4
  min_dets_for_tracks_veh_static: 6
  min_dets_for_tracks_ped: 6
refinement:
  rolling_kbf:
    min_static_score: 0.7
    rolling_kde_window: 16
  propagate_boxes:
    min_dets: 12
    n_extra_frames: 100
    degrade_factor: 0.98
    min_score_clip: 0.5
