exp_name: 'W_L_VMFI_TTA_PA_PC_VA_VC_64' # all files will be named/searched with this as prefix
save_dir: '/MS3D/tools/cfgs/target_lyft/ps_labels_rnd1' 
dataset_cfg: /MS3D/tools/cfgs/dataset_configs/lyft_dataset_da.yaml
ps_score_th: # veh,ped,cyc
  pos_th: [0.6,0.6,0.5]
  neg_th: [0.2,0.1,0.3]
pretrained_kbf:
  discard: [4,4,4]
  radius: [1.5, 0.3, 0.2]
  nms: [0.1, 0.3, 0.1]
tracking:
  veh_all_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1/veh_kf_giou.yaml'
  veh_static_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1/veh_static_kf_iou2d.yaml'
  ped_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1/ped_kf_giou.yaml'
label_refinement:
  track_filtering:
    min_dets_above_pos_th_for_tracks_veh_all: 2
    min_dets_above_pos_th_for_tracks_veh_static: 2
    min_dets_above_pos_th_for_tracks_ped: 1 # ped is tracked with low score, so we say that we only need 1 strong det to determine that it's a ped
    min_num_ped_tracks: 10
  rolling_kbf:
    min_static_score: 0.75
    rolling_kde_window: 20
  propagate_boxes:
    min_static_tracks: 12
    n_extra_frames: 40
    degrade_factor: 0.98
    min_score_clip: 0.3