exp_name: 'RND1_W_N_VMFI_TTA_PA_PC_VA_VC_48_WEIGHTED' # all files will be named/searched with this as prefix
save_dir: '/MS3D/tools/cfgs/target_lyft/ps_labels_rnd1_2' 
dataset_cfg: /MS3D/tools/cfgs/dataset_configs/lyft_dataset_da.yaml
ps_score_th: # veh,ped,cyc
  pos_th: [0.8,0.7,0.5]
  neg_th: [0.2,0.1,0.3]
pretrained_kbf:
  discard: [4,4,4]
  radius: [1.5, 0.3, 0.2]
  nms: [0.1, 0.3, 0.1]
tracking:
  veh_all_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1_2/veh_kf_giou.yaml'
  veh_static_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1_2/veh_static_kf_iou2d.yaml'
  ped_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd1_2/ped_kf_giou.yaml'
label_refinement:
  track_filtering:
    min_dets_above_pos_th_for_tracks_veh_all: 5
    min_dets_above_pos_th_for_tracks_veh_static: 1
    min_dets_above_pos_th_for_tracks_ped: 2
    use_static_ped_tracks: false
    min_num_static_veh_tracks: 7  # not tested on lyft
    min_num_ped_tracks: 10
  rolling_kbf:
    min_static_score: 0.85
    rolling_kde_window: 20
  propagate_boxes:
    min_static_tracks: 25
    n_extra_frames: 100
    degrade_factor: 0.98
    min_score_clip: 0.3
