exp_name: 'RND3_VOXA_VOXC' # all files will be named/searched with this as prefix
save_dir: '/MS3D/tools/cfgs/target_lyft/ps_labels_rnd3' 
dataset_cfg: /MS3D/tools/cfgs/dataset_configs/lyft_dataset_da.yaml
ps_score_th: # veh,ped,cyc
  pos_th: [0.7,0.6,0.5] # loosen the criteria for final self-training round
  neg_th: [0.15,0.1,0.1] # preds get less noisy at lower confidences than earlier stages
pretrained_kbf:
  discard: [1,1,1]
  radius: [1.5, 0.3, 0.2]
  nms: [0.1, 0.3, 0.1]
tracking:
  veh_all_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd3/veh_kf_giou.yaml'
  veh_static_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd3/veh_static_kf_iou2d.yaml'
  ped_cfg: '/MS3D/tracker/configs/lyft/ms3d_configs_rnd3/ped_kf_giou.yaml'
label_refinement:
  track_filtering:
    min_dets_above_pos_th_for_tracks_veh_all: 5
    min_dets_above_pos_th_for_tracks_veh_static: 5
    min_dets_above_pos_th_for_tracks_ped: 0
    min_num_ped_tracks: 10
  rolling_kbf:
    min_static_score: 0.8
    rolling_kde_window: 20
  propagate_boxes:
    min_static_tracks: 10 # Lyft scenes have large ego-motion; you don't often see parked cars for long so this number is lower than waymo
    n_extra_frames: 100
    degrade_factor: 0.99
    min_score_clip: 0.5
