exp_name: 'RND3_VOXA_VOXC' # all files will be named/searched with this as prefix
save_dir: '/MS3D/tools/cfgs/target_nuscenes/ps_labels_rnd3' 
dataset_cfg: /MS3D/tools/cfgs/dataset_configs/nuscenes_dataset_da.yaml
ps_score_th: # veh,ped,cyc
  pos_th: [0.7,0.8,0.5]
  neg_th: [0.15,0.1,0.1]
pretrained_kbf:
  discard: [1,1,1]
  radius: [1.5, 0.3, 0.2]
  nms: [0.1, 0.3, 0.1]
tracking: # Use same track configs as round 2
  veh_all_cfg: '/MS3D/tracker/configs/nuscenes/ms3d_configs_rnd2/veh_kf_giou.yaml'
  veh_static_cfg: '/MS3D/tracker/configs/nuscenes/ms3d_configs_rnd2/veh_static_kf_iou2d.yaml'
  ped_cfg: '/MS3D/tracker/configs/nuscenes/ms3d_configs_rnd2/ped_kf_giou.yaml'
label_refinement:
  track_filtering:
    min_dets_above_pos_th_for_tracks_veh_all: 2
    min_dets_above_pos_th_for_tracks_veh_static: 1
    min_dets_above_pos_th_for_tracks_ped: 0 # We use all moving "pedestrians" but for static pedestrians, we only use those with super high conf (> 0.8)
    min_num_static_veh_tracks: 7
    min_num_ped_tracks: 7 
  propagate_boxes:
    degrade_factor: 0.99
    min_score_clip: 0.3
    min_static_tracks: 10
    n_extra_frames: 40
  rolling_kbf:
    min_static_score: 0.85
    rolling_kde_window: 10

# This is a lenient setting where we just require 1 confident static vehicle observation, and sufficiently long ped tracks (without any confirmation)